name: Swift Build

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: swift build
      run: swift build -v
