name: CI

on:
  pull_request:
    branches:
    - develop
  workflow_dispatch

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute danger
        uses: danger/swift@3.7.1
        with:
            args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.SKELETONVIEW_CI }}
