name: Pod lint
on: [workflow_dispatch]
        
jobs:
  release_version:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
   
      - name: Pod lib lint
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings         
