name: Release
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version"
        required: true
        default: ""
        
jobs:
    pod_lib_lint:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2
            - name: Validate Pod
              env:
                COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
              run: pod lib lint SkeletonView.podspec --allow-warnings
    
    bump_pod_version:
        runs-on: ubuntu-latest
        needs: pod_lib_lint
        steps:
            - run: ./scripts/update_pod_version.sh ${{ github.event.inputs.release_version }}
   
    create_release:
        runs-on: ubuntu-latest
        needs: bump_pod_version
        steps:
            - uses: actions/checkout@v2
            - uses: release-drafter/release-drafter@v5
              with: 
                publish: true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
