name: Release
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version"
        required: true
        default: ""
        
jobs:
    bump_pod_version:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: setup fastlane
            run: brew install fastlane
          - name: bump version
            run: fastlane bump_version next_version:${{ github.event.inputs.release_version }}
    
    commit_changes:
      needs: bump_pod_version
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Commit changes
          run: |
              git config --global user.name 'Juanpe Catalán'
              git config --global user.email 'juanpecm@gmail.com'
              git commit -am 'Bump version ${{ github.event.inputs.release_version }}'
              git push
    
    create_release:
        runs-on: ubuntu-latest
        needs: commit_changes
        steps:
            - uses: actions/checkout@v2
            - uses: release-drafter/release-drafter@v5
              with: 
                publish: true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 
    pod_trunk_repo: 
        runs-on: macOS-latest
        needs: create_release
        steps:
          - uses: actions/checkout@v1
          - name: Publish Pod
            env:
              COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
            run: pod trunk push SkeletonView.podspec --allow-warnings --verbose
