name: Release
on: 
  workflow_dispatch:
    inputs:
      release_version:
        description: "Version"
        required: true
        default: ""
        
jobs:
    pod_lib_lint:
        runs-on: macOS-latest
        steps:
            - uses: actions/checkout@v2
            - name: Validate Pod
              env:
                COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
              run: pod lib lint SkeletonView.podspec --allow-warnings
    
    bump_pod_version:
        runs-on: ubuntu-latest
        needs: pod_lib_lint
        steps:
            - run: ./../../scripts/update_pod_version.sh ${{ github.event.inputs.release_version }}
    
    commit_changes:
      needs: bump_pod_version
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Commit changes
          uses: EndBug/add-and-commit@v7
          with:
            message: 'Bump version ${{ github.event.inputs.release_version }}'
    
    create_release:
        runs-on: ubuntu-latest
        needs: commit_changes
        steps:
            - uses: actions/checkout@v2
            - uses: release-drafter/release-drafter@v5
              with: 
                publish: true
              env:
                 GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                 
    pod_trunk_repo: 
        runs-on: macOS-latest
        needs: create_release
        steps:
          - uses: actions/checkout@v1
          - name: Publish Pod
            env:
              COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
            run: pod trunk push SkeletonView.podspec
