name: Release
on: [workflow_dispatch]
        
jobs:
  release_version:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: setup fastlane
        run: brew install fastlane
            
      - name: publish release
        id: publish_release
        uses: release-drafter/release-drafter@v5
        with: 
          publish: true
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: update podspec file
        run: fastlane bump_version next_version:${{ steps.publish_release.outputs.tag_name }}

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: 'main'
          commit_message: 'Bump version ${{ steps.publish_release.outputs.tag_name }}'
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      

      - name: push pod
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: pod trunk push SkeletonView.podspec --allow-warnings --verbose
