name: SwiftLint

on:
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Lint Action
      uses: wearerequired/lint-action@v1.6.0
      with:
        github_token: ${{ secrets.github_token }}
        swiftlint: true
