name: SwiftLint

on:
  pull_request:
    branches: [ develop ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Run linters
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        swiftlint: true
